<?php

use Nails\Factory;

/**
 * This helper brings some convinient functions for interacting with the captcha module
 *
 * @package     Nails
 * @subpackage  module-captcha
 * @category    Helper
 * @author      Nails Dev Team
 * @link
 */

if (!function_exists('captchaGenerate')) {

    /**
     * Returns the form markup for the captcha
     * @return \Nails\Captcha\Factory\CaptchaForm
     */
    function captchaGenerate()
    {
        $oCaptcha = Factory::service('Captcha', 'nails/module-captcha');
        return $oCaptcha->generate();
    }
}

if (!function_exists('captchaVerify')) {

    /**
     * Verifies a user's captcha entry
     * @return bool
     */
    function captchaVerify()
    {
        $oCaptcha = Factory::service('Captcha', 'nails/module-captcha');
        return $oCaptcha->verify();
    }
}

if (!function_exists('captchaError')) {

    /**
     * Returns the last error generated by the captcha library
     * @return string
     */
    function captchaError()
    {
        $oCaptcha = Factory::service('Captcha', 'nails/module-captcha');
        return $oCaptcha->lastError();
    }
}
